---
title: "ANOVA_test"
output: 
  html_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(cmdstanr, tidyverse, here, ggplot2, future, future.apply, bayesplot, patchwork)
```


## simulate 1 dataset 
```{r}
J = 34
n = 3

N = n*J

pop_mean = rnorm(1, 0, 1)
pop_sigma = rexp(1, rate = 1)

sigma_res = rexp(1, rate = 1)

rand_intercepts = rnorm(J, pop_mean, pop_sigma)

animal = rep(1:J, each = n)               

beta_int = rnorm(1,0,1)
beta_env = rnorm(1,0,1)
beta_t = rnorm(1,0,1)

treatment = sample(c(0, 1), J, replace = TRUE)
env       = sample(c(0, 1), J, replace = TRUE)

treatment = treatment[animal]      
env       = env[animal] 

mu =rand_intercepts[animal] + beta_env*env + beta_t*treatment + beta_int*(treatment*env)
y = rnorm(N, mu, sigma_res)


dat = data.frame(
  animal    = animal,
  trial     = rep(1:n, times = J),
  y         = y,
  treatment = treatment,
  env       = env
)

true_values = c(NA,pop_mean,pop_sigma,beta_int,beta_env,beta_t,sigma_res,rep(NA, times = 34), rand_intercepts = rand_intercepts, rep(NA, times = 11))


```


## Fit 1 dataset
```{r pressure, echo=FALSE}
data_stan = list(N = N, y = y, treatment = treatment, environment=env, J =J, animal = animal)

model = cmdstan_model(here("Data Analysis", "Analysis tests", "TF", "ANOVA_TF.stan"))

fit = model$sample(data = data_stan, iter_warmup =500, iter_sampling = 500, chains = 4, parallel_chains = 4, adapt_delta = 0.95, max_treedepth = 12)
```
## evaluate fit
```{r}
summary = fit$summary()
summary$sim = true_values

summary


```






## Generate multiple data sets
```{r}
sim = 200

sim_list = list()

for(i in 1:sim){
  
    J = 34
    n = 3
    
    N = n*J
    
    pop_mean = rnorm(1, 0, 1)
    pop_sigma = rexp(1, rate = 1)
    
    sigma_res = rexp(1, rate = 1)
    
    rand_intercepts = rnorm(J, pop_mean, pop_sigma)
    
    animal = rep(1:J, each = n)               
    
    beta_int = rnorm(1,0,1)
    beta_env = rnorm(1,0,1)
    beta_t = rnorm(1,0,1)
    
    treatment = sample(c(0, 1), J, replace = TRUE)
    env       = sample(c(0, 1), J, replace = TRUE)
    
    treatment = treatment[animal]      
    env       = env[animal] 
    
    mu =rand_intercepts[animal] + beta_env*env + beta_t*treatment + beta_int*(treatment*env)
    y = rnorm(N, mu, sigma_res)
    
    
    sim_data  = data.frame(animal    = animal,trial     = rep(1:n, times = J),y         = y,
    treatment = treatment,env       = env)
    
 
    true_values = c(NA,pop_mean,pop_sigma,beta_int,beta_env,beta_t,sigma_res,rep(NA, times = 34), rand_intercepts, rep(NA, times = 11))
  

  
    sim_list[[i]] = list(sim_data = sim_data, sim_vals = true_values)
  
}

```


## Fit model sim times
```{r, echo = FALSE, message=FALSE}
n_cores = availableCores()
use_cores = max(1, n_cores - 4)

plan(multisession, workers = use_cores)

model = cmdstan_model(here("Data Analysis", "Analysis tests", "TF", "ANOVA_TF.stan"))

fits = future_lapply(seq_len(sim), function(i) {
  df = sim_list[[i]][[1]]
  
  data_stan <- list(N = 102,y = df$y,treatment = df$treatment,environment = df$env, animal = df$animal,J=34)
  
  fit <- model$sample(data = data_stan,iter_warmup = 1000,iter_sampling = 2000,chains = 4,parallel_chains = 4,refresh = 0, adapt_delta = 0.95)
  
  summary <- fit$summary()
  
  
  summary$sim <- sim_list[[i]][[2]]
  summary
  })
```


## check parameter recovery
```{r}
result <- bind_rows(fits, .id = "sim_id")

mu_alpha = result %>% 
  filter(variable == "mu_alpha") %>% 
  ggplot() +
  geom_pointrange(aes(x = sim, y = mean, ymin = q5, ymax = q95), color = "black")+
  geom_abline(intercept = 0, slope = 1, linewidth = 1.5, color = "red", linetype = "dashed")+
  theme_classic(base_size =20)+labs(title = expression(mu))+theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
                                                                  axis.line = element_line(linewidth = 1.5))


beta_int = result %>% 
  filter(variable == "beta_int") %>% 
  ggplot() +
  geom_pointrange(aes(x = sim, y = mean, ymin = q5, ymax = q95), color = "black")+
  geom_abline(intercept = 0, slope = 1, linewidth = 1.5, color = "red", linetype = "dashed")+
  theme_classic(base_size =20)+labs(title = expression(beta[int]))+theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
                                                                  axis.line = element_line(linewidth = 1.5))  

beta_env = result %>% 
  filter(variable == "beta_env") %>% 
  ggplot() +
  geom_pointrange(aes(x = sim, y = mean, ymin = q5, ymax = q95), color = "black")+
  geom_abline(intercept = 0, slope = 1, linewidth = 1.5, color = "red", linetype = "dashed")+
  theme_classic(base_size =20)+labs(title = expression(beta[env]))+theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
                                                                  axis.line = element_line(linewidth = 1.5))  

beta_t = result %>% 
  filter(variable == "beta_t") %>% 
  ggplot() +
  geom_pointrange(aes(x = sim, y = mean, ymin = q5, ymax = q95), color = "black")+
  geom_abline(intercept = 0, slope = 1, linewidth = 1.5, color = "red", linetype = "dashed")+
  theme_classic(base_size =20)+labs(title = expression(beta[t]))+theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
                                                                  axis.line = element_line(linewidth = 1.5))  
sigma_res = result %>% 
  filter(variable == "sigma") %>% 
  ggplot() +
  geom_pointrange(aes(x = sim, y = mean, ymin = q5, ymax = q95), color = "black")+
  geom_abline(intercept = 0, slope = 1, linewidth = 1.5, color = "red", linetype = "dashed")+
  theme_classic(base_size =20)+labs(title = expression(sigma[res]))+theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
                                                                  axis.line = element_line(linewidth = 1.5)) 

sigma_alpha = result %>% 
  filter(variable == "sigma_alpha") %>% 
  ggplot() +
  geom_pointrange(aes(x = sim, y = mean, ymin = q5, ymax = q95), color = "black")+
  geom_abline(intercept = 0, slope = 1, linewidth = 1.5, color = "red", linetype = "dashed")+
  theme_classic(base_size =20)+labs(title = expression(sigma[group]))+theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
                                                                  axis.line = element_line(linewidth = 1.5)) 

(beta_int|beta_env|beta_t)/
  (mu_alpha|sigma_res|sigma_alpha)
```

























